### PR TITLE
added stuff

### PR DESCRIPTION
**Pull request by pike168**

### CODE REVIEW

**Comment by TGoodall** [comment]
could you fix header,
Thanks.

**Comment by pike168** [comment]
> could you fix header

### More Details Please?
How about **these** changes:

1.change main.c
2.change README

This _could_ cause: 
- faster program
- easier to debug

Would you like me to:

- [ ] close this pull request, fix and then create a new
- [ ] change diff's

**Comment by pike168** [comment]
Are these changes adequate?

**Comment by TGoodall** [comment]
All good,
Will now merge.
Thanks.

**Pull request merged**
